### ISSUE TITLE
Your npm published  0.1.0 package does not match 0.1.0 on this repo

### ISSUE THREAD

**Issue by joaojeronimo** [craigbilner/react-component-tester#258]
On this repo `0.1.0` depends on [react and react-addons-test-utils 15.1.0](https://github.com/craigbilner/react-component-tester/blob/master/package.json#L59-L60) but after installing the npm package you will get a `0.1.0` that depends on versions `0.14.7` of those packages.

Can you please `npm publish` ? In case whatever is on the tip of this repo's master is not ready for publishing I think it's a good idea to set package.json to 0.1.1-beta or similar.

**Comment by craigbilner** [comment]
All updated, thanks for whipping me into shape :-)

**Comment by joaojeronimo** [comment]
Thanks Craig 💃
